const PDFDocument = require('pdfkit');
const analyticsService = require('./analytics.service');
const Hospital = require('../models/Hospital');

/**
 * Generates a clean PDF report for a specific day.
 * @param {string} dateStr - YYYY-MM-DD format
 * @returns {PDFDocument} - The PDFKit document stream
 */
const generateDailyPDFReport = async (dateStr) => {
  const stats = await analyticsService.getDashboardAnalytics(dateStr);
  const hospital = await Hospital.findOne();
  const dateFormatted = new Date(dateStr || new Date()).toLocaleDateString();

  const doc = new PDFDocument({ margin: 50 });

  // 1. Header
  doc.fontSize(20).text('MediQueue Daily Operations Report', { align: 'center' });
  doc.fontSize(12).text(`Hospital: ${hospital?.name || 'MediQueue General'}`, { align: 'center' });
  doc.text(`Date: ${dateFormatted}`, { align: 'center' });
  doc.moveDown(2);

  // 2. Summary Section
  doc.fontSize(16).text('1. Operations Summary', { underline: true });
  doc.fontSize(12).moveDown(0.5);
  doc.text(`Total Patients Registered: ${stats.summary.totalRegistered}`);
  doc.text(`Total Consultations Completed: ${stats.summary.totalCompleted}`);
  doc.text(`Patients Currently Waiting: ${stats.summary.totalWaiting}`);
  doc.text(`Patients Currently Called: ${stats.summary.totalCalled}`);
  doc.moveDown();

  // 3. Department Breakdown
  doc.fontSize(16).text('2. Department Performance', { underline: true });
  doc.moveDown(0.5);
  stats.departmentBreakdown.forEach(dept => {
    doc.fontSize(12).text(`${dept.name}:`, { indent: 20 });
    doc.fontSize(11).text(`- Registered: ${dept.totalRegistered}`, { indent: 40 });
    doc.text(`- Completed: ${dept.completed}`, { indent: 40 });
    doc.text(`- Avg Wait Time: ${dept.avgWaitTimeMinutes.toFixed(1)} mins`, { indent: 40 });
    doc.moveDown(0.2);
  });
  doc.moveDown();

  // 4. Triage Distribution
  doc.fontSize(16).text('3. Triage & Urgency Mix', { underline: true });
  doc.moveDown(0.5);
  stats.triageDistribution.forEach(t => {
    doc.fontSize(12).text(`${t.urgency.toUpperCase()}: ${t.count} patients`, { indent: 20 });
  });
  doc.moveDown();

  // 5. Peak Load Highlights
  doc.fontSize(16).text('4. Peak Load Windows', { underline: true });
  doc.moveDown(0.5);
  const topBuckets = [...stats.peakLoadTimeSeries]
    .sort((a, b) => b.registrations - a.registrations)
    .slice(0, 3);
  
  if (topBuckets.length > 0) {
    topBuckets.forEach(b => {
      doc.fontSize(12).text(`${b.time}: ${b.registrations} registrations`, { indent: 20 });
    });
  } else {
    doc.fontSize(12).text('No registration data available for this day.', { indent: 20 });
  }

  // Footer
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    doc.fontSize(10).text(
      'Generated by MediQueue Admin Dashboard',
      50,
      doc.page.height - 50,
      { align: 'center' }
    );
  }

  return doc;
};

module.exports = {
  generateDailyPDFReport
};
